---
- name: Enable i3-gaps repository
  become: true
  command: dnf copr enable -y fuhrmann/i3-gaps

- name: Install i3 and related programs
  become: true
  package:
    name: "{{ item }}"
    state: latest
  loop:
   - i3-gaps
   - i3lock
   - i3status 
   - polybar
   - rofi
   - feh
   - playerctl
   - terminator
