---
- name: Install favorite command line tools
  become: true
  package:
    name: "{{ item }}"
    state: latest
  loop: 
    - neovim
    - python3-neovim
    - lsd

- name: Create vim directories
  file: 
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: Install plug.vim
  get_url:
   url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
   dest: ~/.local/share/nvim/site/autoload/plug.vim
