---
- name: Get a local copy of my dotfiles
  git:
    repo=git@github.com:MichaelAnckaert/dotfiles.git
    dest=~/.dotfiles
    accept_hostkey=yes

- name: Link dotfiles
  command: bash ~/.dotfiles/install.sh || true
